apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deplyment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gcr.io/higgy-ekss/pyhon-webapp:latest
        env:
          - name: REDIS_HOST
            value: "redis"
        ports:
          - containerPort: 8000
